name: Nightly Build And Compile Test
  
on: 
  push: 
    tags: 
      - "*" 
  # Make sure it can be uploaded when a PR is requested - Vizonex
  pull_request:
    tags:
      - "*"
  workflow_dispatch: 
    
permissions:
  contents: read
  

jobs:
  build_wheels: 
    name: Build wheels 
    runs-on: windows-latest
        
    steps: 
      - uses: actions/checkout@v3 

      - uses: actions/setup-python@v4 
        with: 
          python-version: "3.x"
  
      - name: Install cibuildwheel 
        run: pip install cibuildwheel -qq 
      
      
      - name: Build wheels 
        run: python -m cibuildwheel --output-dir wheelhouse 
        env: 
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*" 
          CIBW_SKIP: "pp* *-win_arm64 *-win32"

      - uses: actions/upload-artifact@v3 
        with: 
          name: dist
          path: ./wheelhouse/*.whl 
  
  
  build_sdist:
    name: Build source distribution
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4 
        with: 
          python-version: "3.x"
          
      - name: Install Setuptools 
        run: python -m pip install --upgrade setuptools wheel pip cython
        
      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          came: dist
          path: ./dist/*
      
    
